//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_BareboatCharter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_BareboatCharter() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Pages.BareboatCharter", typeof(Pages_BareboatCharter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perfect technical condition of the fleet, guaranteed.
        /// </summary>
        internal static string Bareboat_Benefit1 {
            get {
                return ResourceManager.GetString("Bareboat_Benefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excellent service and friendly staff.
        /// </summary>
        internal static string Bareboat_Benefit2 {
            get {
                return ResourceManager.GetString("Bareboat_Benefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  No hidden fees, transparent conditions.
        /// </summary>
        internal static string Bareboat_Benefit3 {
            get {
                return ResourceManager.GetString("Bareboat_Benefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free boat handling refresher at handover.
        /// </summary>
        internal static string Bareboat_Benefit4 {
            get {
                return ResourceManager.GetString("Bareboat_Benefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Why choose us?.
        /// </summary>
        internal static string Bareboat_Benefits_Title {
            get {
                return ResourceManager.GetString("Bareboat_Benefits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Request.
        /// </summary>
        internal static string Bareboat_Contact_Button {
            get {
                return ResourceManager.GetString("Bareboat_Contact_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready to set sail?.
        /// </summary>
        internal static string Bareboat_Contact_Title {
            get {
                return ResourceManager.GetString("Bareboat_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For those short on time, we offer full-day yacht rental (Day Charter) in Montenegro. Enjoy a relaxing day at sea, exploring the stunning coast with an experienced skipper..
        /// </summary>
        internal static string Bareboat_Day_Text {
            get {
                return ResourceManager.GetString("Bareboat_Day_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day Yacht Charter.
        /// </summary>
        internal static string Bareboat_Day_Title {
            get {
                return ResourceManager.GetString("Bareboat_Day_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refundable security deposit taken at check-in as a guarantee for the yacht and its equipment. Damage Waiver available at €30 per day..
        /// </summary>
        internal static string Bareboat_Deposit_Text {
            get {
                return ResourceManager.GetString("Bareboat_Deposit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Security deposit = 2000 €.
        /// </summary>
        internal static string Bareboat_Deposit_Title {
            get {
                return ResourceManager.GetString("Bareboat_Deposit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на discount for Sail Band Sailing School alumni.
        /// </summary>
        internal static string Bareboat_Discount_Alumni {
            get {
                return ResourceManager.GetString("Bareboat_Discount_Alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на discount for last-minute booking (contract signed &lt; 10 days before start).
        /// </summary>
        internal static string Bareboat_Discount_LastMinute {
            get {
                return ResourceManager.GetString("Bareboat_Discount_LastMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на discount for long-term charter (10% off second week, 15% off third week).
        /// </summary>
        internal static string Bareboat_Discount_LongTerm {
            get {
                return ResourceManager.GetString("Bareboat_Discount_LongTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Maximum total discount is 15%..
        /// </summary>
        internal static string Bareboat_Discount_Note {
            get {
                return ResourceManager.GetString("Bareboat_Discount_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DISCOUNTS!.
        /// </summary>
        internal static string Bareboat_Discounts_Title {
            get {
                return ResourceManager.GetString("Bareboat_Discounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Includes a trolling rod with reel and line, a set of lures, a gaff, and a rod holder for the rail..
        /// </summary>
        internal static string Bareboat_Extra_Fishing_Text {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Fishing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fishing gear .
        /// </summary>
        internal static string Bareboat_Extra_Fishing_Title {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Fishing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Halyard and sheets are provided..
        /// </summary>
        internal static string Bareboat_Extra_Gennaker_Text {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Gennaker_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gennaker .
        /// </summary>
        internal static string Bareboat_Extra_Gennaker_Title {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Gennaker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you have nothing to do in the evenings..
        /// </summary>
        internal static string Bareboat_Extra_Poker_Text {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Poker_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poker set .
        /// </summary>
        internal static string Bareboat_Extra_Poker_Title {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Poker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you don’t have a skipper license, you can rent with a captain..
        /// </summary>
        internal static string Bareboat_Extra_Skipper_Text {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Skipper_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skipper .
        /// </summary>
        internal static string Bareboat_Extra_Skipper_Title {
            get {
                return ResourceManager.GetString("Bareboat_Extra_Skipper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additionally.
        /// </summary>
        internal static string Bareboat_Extras_Title {
            get {
                return ResourceManager.GetString("Bareboat_Extras_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Request.
        /// </summary>
        internal static string Bareboat_Form_Button {
            get {
                return ResourceManager.GetString("Bareboat_Form_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Bareboat_Form_Email {
            get {
                return ResourceManager.GetString("Bareboat_Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send a request and we’ll contact you with a personal discount offer..
        /// </summary>
        internal static string Bareboat_Form_Intro {
            get {
                return ResourceManager.GetString("Bareboat_Form_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Bareboat_Form_Name {
            get {
                return ResourceManager.GetString("Bareboat_Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        internal static string Bareboat_Form_Phone {
            get {
                return ResourceManager.GetString("Bareboat_Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you! Your request has been sent. We will contact you shortly..
        /// </summary>
        internal static string Bareboat_Form_Success {
            get {
                return ResourceManager.GetString("Bareboat_Form_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send us a Request.
        /// </summary>
        internal static string Bareboat_Form_Title {
            get {
                return ResourceManager.GetString("Bareboat_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Learn more.
        /// </summary>
        internal static string Bareboat_Hero_CTA {
            get {
                return ResourceManager.GetString("Bareboat_Hero_CTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8 identical sailing yachts (and one motor yacht) at 5★ Porto Montenegro marina.
        /// </summary>
        internal static string Bareboat_Hero_Subtitle {
            get {
                return ResourceManager.GetString("Bareboat_Hero_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dinghy with outboard motor.
        /// </summary>
        internal static string Bareboat_Included_Item1 {
            get {
                return ResourceManager.GetString("Bareboat_Included_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bed linens, towels, and all necessary items.
        /// </summary>
        internal static string Bareboat_Included_Item2 {
            get {
                return ResourceManager.GetString("Bareboat_Included_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Berth in Porto Montenegro marina.
        /// </summary>
        internal static string Bareboat_Included_Item3 {
            get {
                return ResourceManager.GetString("Bareboat_Included_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insurance.
        /// </summary>
        internal static string Bareboat_Included_Item4 {
            get {
                return ResourceManager.GetString("Bareboat_Included_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Galley gas cylinders.
        /// </summary>
        internal static string Bareboat_Included_Item5 {
            get {
                return ResourceManager.GetString("Bareboat_Included_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Onboard Wi-Fi in Montenegro (5 GB).
        /// </summary>
        internal static string Bareboat_Included_Item6 {
            get {
                return ResourceManager.GetString("Bareboat_Included_Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Included in price.
        /// </summary>
        internal static string Bareboat_Included_Title {
            get {
                return ResourceManager.GetString("Bareboat_Included_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Final cleaning.
        /// </summary>
        internal static string Bareboat_NotIncluded_Item1 {
            get {
                return ResourceManager.GetString("Bareboat_NotIncluded_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel (return with full tank).
        /// </summary>
        internal static string Bareboat_NotIncluded_Item2 {
            get {
                return ResourceManager.GetString("Bareboat_NotIncluded_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not included in price.
        /// </summary>
        internal static string Bareboat_NotIncluded_Title {
            get {
                return ResourceManager.GetString("Bareboat_NotIncluded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на until March 30 — 2 300 €.
        /// </summary>
        internal static string Bareboat_Rate1 {
            get {
                return ResourceManager.GetString("Bareboat_Rate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mar 30 – Apr 22 — 2 800 €.
        /// </summary>
        internal static string Bareboat_Rate2 {
            get {
                return ResourceManager.GetString("Bareboat_Rate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apr 22 – Jun 15 — 3 300 €.
        /// </summary>
        internal static string Bareboat_Rate3 {
            get {
                return ResourceManager.GetString("Bareboat_Rate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jun 15 – Jun 29 — 3 700 €.
        /// </summary>
        internal static string Bareboat_Rate4 {
            get {
                return ResourceManager.GetString("Bareboat_Rate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jun 29 – Aug 24 — 4 300 €.
        /// </summary>
        internal static string Bareboat_Rate5 {
            get {
                return ResourceManager.GetString("Bareboat_Rate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aug 24 – Oct 5 — 3 700 €.
        /// </summary>
        internal static string Bareboat_Rate6 {
            get {
                return ResourceManager.GetString("Bareboat_Rate6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oct 5 – Nov 9 — 3 000 €.
        /// </summary>
        internal static string Bareboat_Rate7 {
            get {
                return ResourceManager.GetString("Bareboat_Rate7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from Nov 9 — 2 300 €.
        /// </summary>
        internal static string Bareboat_Rate8 {
            get {
                return ResourceManager.GetString("Bareboat_Rate8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price for 1 week of charter. Standard charter week is from 17:00 Saturday to 10:00 next Saturday..
        /// </summary>
        internal static string Bareboat_Rates_Subtitle {
            get {
                return ResourceManager.GetString("Bareboat_Rates_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rental rates.
        /// </summary>
        internal static string Bareboat_Rates_Title {
            get {
                return ResourceManager.GetString("Bareboat_Rates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekly Yacht Charter.
        /// </summary>
        internal static string Bareboat_Rates_Week_Title {
            get {
                return ResourceManager.GetString("Bareboat_Rates_Week_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yachting in Montenegro.
        /// </summary>
        internal static string Bareboat_Title {
            get {
                return ResourceManager.GetString("Bareboat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For those seeking an extended sailing experience, we offer weekly yacht rental in Montenegro. Spend an unforgettable week exploring scenic bays and islands accompanied by an experienced skipper..
        /// </summary>
        internal static string Bareboat_Week_Text {
            get {
                return ResourceManager.GetString("Bareboat_Week_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rent a yacht without skipper in Montenegro! Bareboat charters for experienced sailors: large fleet, transparent rates, full support, and expert advice. Plan your own sailing adventure with VibeOfTheWave..
        /// </summary>
        internal static string Meta_Description_BareboatCharter {
            get {
                return ResourceManager.GetString("Meta_Description_BareboatCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Yacht Charter Montenegro — Rent Without Skipper | VibeOfTheWave.
        /// </summary>
        internal static string PageTitle_BareboatCharter {
            get {
                return ResourceManager.GetString("PageTitle_BareboatCharter", resourceCulture);
            }
        }
    }
}
