//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Management {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Management() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Pages.Management", typeof(Pages_Management).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на after which you can decide whether you need the service or not..
        /// </summary>
        internal static string Management_Form_AfterListNote {
            get {
                return ResourceManager.GetString("Management_Form_AfterListNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will discuss all the details,.
        /// </summary>
        internal static string Management_Form_Benefit1 {
            get {
                return ResourceManager.GetString("Management_Form_Benefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на calculate the mooring cost based on your yacht’s size,.
        /// </summary>
        internal static string Management_Form_Benefit2 {
            get {
                return ResourceManager.GetString("Management_Form_Benefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and send a contract outlining the free maintenance schedule,.
        /// </summary>
        internal static string Management_Form_Benefit3 {
            get {
                return ResourceManager.GetString("Management_Form_Benefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email Address.
        /// </summary>
        internal static string Management_Form_Email_Label {
            get {
                return ResourceManager.GetString("Management_Form_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Management_Form_Name_Label {
            get {
                return ResourceManager.GetString("Management_Form_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feel free to send a request – it doesn’t commit you to anything..
        /// </summary>
        internal static string Management_Form_Note {
            get {
                return ResourceManager.GetString("Management_Form_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number.
        /// </summary>
        internal static string Management_Form_Phone_Label {
            get {
                return ResourceManager.GetString("Management_Form_Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are welcome to visit us in Montenegro at our dock to meet us in person, assess the level and reliability of Porto Montenegro Marina and, most importantly, see the condition of our boats and how we take care of them..
        /// </summary>
        internal static string Management_Form_Reassurance1 {
            get {
                return ResourceManager.GetString("Management_Form_Reassurance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It’s no secret that charter yachts are subjected to heavy wear and tear because clients are not always careful. If we manage to keep our fleet in perfect condition even under such conditions, you can be confident that you are entrusting your beauty to reliable hands..
        /// </summary>
        internal static string Management_Form_Reassurance2 {
            get {
                return ResourceManager.GetString("Management_Form_Reassurance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Request.
        /// </summary>
        internal static string Management_Form_SubmitButton {
            get {
                return ResourceManager.GetString("Management_Form_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your request has been sent successfully!.
        /// </summary>
        internal static string Management_Form_Success {
            get {
                return ResourceManager.GetString("Management_Form_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact Us to Discuss the Details.
        /// </summary>
        internal static string Management_Form_Title {
            get {
                return ResourceManager.GetString("Management_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yacht Size (ft).
        /// </summary>
        internal static string Management_Form_YachtSize_Label {
            get {
                return ResourceManager.GetString("Management_Form_YachtSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What type of yacht do you have?.
        /// </summary>
        internal static string Management_Form_YachtType_Label {
            get {
                return ResourceManager.GetString("Management_Form_YachtType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motor.
        /// </summary>
        internal static string Management_Form_YachtType_Motor {
            get {
                return ResourceManager.GetString("Management_Form_YachtType_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sailing.
        /// </summary>
        internal static string Management_Form_YachtType_Sail {
            get {
                return ResourceManager.GetString("Management_Form_YachtType_Sail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Request.
        /// </summary>
        internal static string Management_HeroCTA {
            get {
                return ResourceManager.GetString("Management_HeroCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vibe of the Waves.
        /// </summary>
        internal static string Management_HeroHeadlinePart1 {
            get {
                return ResourceManager.GetString("Management_HeroHeadlinePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MANAGEMENT.
        /// </summary>
        internal static string Management_HeroHeadlinePart2 {
            get {
                return ResourceManager.GetString("Management_HeroHeadlinePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service for Yacht Owners.
        /// </summary>
        internal static string Management_HeroSubheadline {
            get {
                return ResourceManager.GetString("Management_HeroSubheadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your yacht will receive care, attention, and maintenance according to a strict schedule outlined in our contract. Before your arrival, the yacht will be fully prepared (rigged, cleaned, beds made, water tanks filled with fresh water, all departure documents ready). All you have to do is start the serviced engine and enjoy your vacation..
        /// </summary>
        internal static string Management_Offer_HowItWorks_Text {
            get {
                return ResourceManager.GetString("Management_Offer_HowItWorks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How it Works.
        /// </summary>
        internal static string Management_Offer_HowItWorks_Title {
            get {
                return ResourceManager.GetString("Management_Offer_HowItWorks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you’re reading this, chances are you either already own a yacht or are planning to buy one. In either case, this page is for you, and there are three important points you should know:.
        /// </summary>
        internal static string Management_Offer_Intro {
            get {
                return ResourceManager.GetString("Management_Offer_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Essence of the Offer.
        /// </summary>
        internal static string Management_Offer_Point1_Subtitle {
            get {
                return ResourceManager.GetString("Management_Offer_Point1_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will berth your yacht at our dock in Porto Montenegro Marina at the official marina rate and provide free year-round technical maintenance. We work with both sailing and motor yachts. Annual mooring from €4400; winter mooring (October–April) from €2580. The exact cost depends on your yacht’s size..
        /// </summary>
        internal static string Management_Offer_Point1_Text {
            get {
                return ResourceManager.GetString("Management_Offer_Point1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offer for Yacht Owners.
        /// </summary>
        internal static string Management_Offer_Title {
            get {
                return ResourceManager.GetString("Management_Offer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year-round technical maintenance is free of charge!.
        /// </summary>
        internal static string Management_Parking_Advantage1 {
            get {
                return ResourceManager.GetString("Management_Parking_Advantage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We keep your yacht in perfect condition.
        /// </summary>
        internal static string Management_Parking_Advantage2 {
            get {
                return ResourceManager.GetString("Management_Parking_Advantage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have nothing to worry about – just enjoy the sea and your vacation.
        /// </summary>
        internal static string Management_Parking_Advantage3 {
            get {
                return ResourceManager.GetString("Management_Parking_Advantage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from €4400.
        /// </summary>
        internal static string Management_Parking_Annual_Price {
            get {
                return ResourceManager.GetString("Management_Parking_Annual_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Annual mooring.
        /// </summary>
        internal static string Management_Parking_Annual_Title {
            get {
                return ResourceManager.GetString("Management_Parking_Annual_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docking at Porto Montenegro – the finest marina in the Adriatic.
        /// </summary>
        internal static string Management_Parking_Title {
            get {
                return ResourceManager.GetString("Management_Parking_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на from €2580.
        /// </summary>
        internal static string Management_Parking_Winter_Price {
            get {
                return ResourceManager.GetString("Management_Parking_Winter_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winter mooring (October–April).
        /// </summary>
        internal static string Management_Parking_Winter_Title {
            get {
                return ResourceManager.GetString("Management_Parking_Winter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your yacht is always in perfect condition and ready to take you or your friends on board and head out to sea at a moment’s notice..
        /// </summary>
        internal static string Management_Wishes_Option1_Text {
            get {
                return ResourceManager.GetString("Management_Wishes_Option1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I don’t want to see strangers on my beautiful yacht.
        /// </summary>
        internal static string Management_Wishes_Option1_Title {
            get {
                return ResourceManager.GetString("Management_Wishes_Option1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We will rent out your yacht, but only with our own skipper whom we trust. We take full responsibility..
        /// </summary>
        internal static string Management_Wishes_Option2_Text {
            get {
                return ResourceManager.GetString("Management_Wishes_Option2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I want to cover part of the expenses, but I’m not ready to trust my yacht to just anyone.
        /// </summary>
        internal static string Management_Wishes_Option2_Title {
            get {
                return ResourceManager.GetString("Management_Wishes_Option2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No problem. We will charter out your yacht exactly the way we charter our own yachts..
        /// </summary>
        internal static string Management_Wishes_Option3_Text {
            get {
                return ResourceManager.GetString("Management_Wishes_Option3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I want to earn and achieve the maximum profit.
        /// </summary>
        internal static string Management_Wishes_Option3_Title {
            get {
                return ResourceManager.GetString("Management_Wishes_Option3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decide on Your Preferences.
        /// </summary>
        internal static string Management_Wishes_Title {
            get {
                return ResourceManager.GetString("Management_Wishes_Title", resourceCulture);
            }
        }
    }
}
