//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_SchoolPower {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_SchoolPower() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Pages.SchoolPower", typeof(Pages_SchoolPower).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back to home.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 days.
        /// </summary>
        internal static string ProgramDetails_Duration {
            get {
                return ResourceManager.GetString("ProgramDetails_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration.
        /// </summary>
        internal static string ProgramDetails_DurationLabel {
            get {
                return ResourceManager.GetString("ProgramDetails_DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beginner.
        /// </summary>
        internal static string ProgramDetails_Level {
            get {
                return ResourceManager.GetString("ProgramDetails_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        internal static string ProgramDetails_LevelLabel {
            get {
                return ResourceManager.GetString("ProgramDetails_LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 850 €.
        /// </summary>
        internal static string ProgramDetails_Price {
            get {
                return ResourceManager.GetString("ProgramDetails_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string ProgramDetails_PriceLabel {
            get {
                return ResourceManager.GetString("ProgramDetails_PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This 3-day intensive will give you confidence behind the wheel of a motor yacht..
        /// </summary>
        internal static string ProgramDetails_Text {
            get {
                return ResourceManager.GetString("ProgramDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Course details.
        /// </summary>
        internal static string ProgramDetails_Title {
            get {
                return ResourceManager.GetString("ProgramDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select course.
        /// </summary>
        internal static string Programs_SelectCourse {
            get {
                return ResourceManager.GetString("Programs_SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Master throttle and handling of motor yachts.
        /// </summary>
        internal static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confident Start — Powerboats.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engine operation and safety checks.
        /// </summary>
        internal static string WhatYouLearn_Item1 {
            get {
                return ResourceManager.GetString("WhatYouLearn_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docking and manoeuvring in tight spaces.
        /// </summary>
        internal static string WhatYouLearn_Item2 {
            get {
                return ResourceManager.GetString("WhatYouLearn_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basic navigation and chart reading.
        /// </summary>
        internal static string WhatYouLearn_Item3 {
            get {
                return ResourceManager.GetString("WhatYouLearn_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What you’ll learn.
        /// </summary>
        internal static string WhatYouLearn_Title {
            get {
                return ResourceManager.GetString("WhatYouLearn_Title", resourceCulture);
            }
        }
    }
}
