//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Tours {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Tours() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Pages.Tours", typeof(Pages_Tours).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photo &amp; Video service available on request.
        /// </summary>
        internal static string Tours_Advantage1 {
            get {
                return ResourceManager.GetString("Tours_Advantage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flexible timing: half-day or full-day options.
        /// </summary>
        internal static string Tours_Advantage2 {
            get {
                return ResourceManager.GetString("Tours_Advantage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catering service: finger food, salads, drinks.
        /// </summary>
        internal static string Tours_Advantage3 {
            get {
                return ResourceManager.GetString("Tours_Advantage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exclusive use: just your group on board.
        /// </summary>
        internal static string Tours_Advantage4 {
            get {
                return ResourceManager.GetString("Tours_Advantage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional Perks.
        /// </summary>
        internal static string Tours_Advantages_Title {
            get {
                return ResourceManager.GetString("Tours_Advantages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unforgettable atmosphere on the open sea.
        /// </summary>
        internal static string Tours_Benefit1 {
            get {
                return ResourceManager.GetString("Tours_Benefit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Professional captain ensures your safety.
        /// </summary>
        internal static string Tours_Benefit2 {
            get {
                return ResourceManager.GetString("Tours_Benefit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customizable routes along the stunning coast.
        /// </summary>
        internal static string Tours_Benefit3 {
            get {
                return ResourceManager.GetString("Tours_Benefit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All-inclusive yacht and crew.
        /// </summary>
        internal static string Tours_Benefit4 {
            get {
                return ResourceManager.GetString("Tours_Benefit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Why Celebrate on a Yacht?.
        /// </summary>
        internal static string Tours_Benefits_Title {
            get {
                return ResourceManager.GetString("Tours_Benefits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Book Your Tour.
        /// </summary>
        internal static string Tours_CTA_Button {
            get {
                return ResourceManager.GetString("Tours_CTA_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready to Party on Deck?.
        /// </summary>
        internal static string Tours_CTA_Title {
            get {
                return ResourceManager.GetString("Tours_CTA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Request.
        /// </summary>
        internal static string Tours_Form_Button {
            get {
                return ResourceManager.GetString("Tours_Form_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Date.
        /// </summary>
        internal static string Tours_Form_Date {
            get {
                return ResourceManager.GetString("Tours_Form_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email Address.
        /// </summary>
        internal static string Tours_Form_Email {
            get {
                return ResourceManager.GetString("Tours_Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of Guests.
        /// </summary>
        internal static string Tours_Form_Guests {
            get {
                return ResourceManager.GetString("Tours_Form_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Name.
        /// </summary>
        internal static string Tours_Form_Name {
            get {
                return ResourceManager.GetString("Tours_Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone Number.
        /// </summary>
        internal static string Tours_Form_Phone {
            get {
                return ResourceManager.GetString("Tours_Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you! Your request has been sent. We will contact you soon..
        /// </summary>
        internal static string Tours_Form_Success {
            get {
                return ResourceManager.GetString("Tours_Form_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request a Party Tour.
        /// </summary>
        internal static string Tours_Form_Title {
            get {
                return ResourceManager.GetString("Tours_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gallery Preview.
        /// </summary>
        internal static string Tours_Gallery_Title {
            get {
                return ResourceManager.GetString("Tours_Gallery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discover More.
        /// </summary>
        internal static string Tours_Hero_CTA {
            get {
                return ResourceManager.GetString("Tours_Hero_CTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Experienced captain at the helm.
        /// </summary>
        internal static string Tours_Service_Captain {
            get {
                return ResourceManager.GetString("Tours_Service_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scenic coastal route planning.
        /// </summary>
        internal static string Tours_Service_Route {
            get {
                return ResourceManager.GetString("Tours_Service_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modern and fully equipped yacht.
        /// </summary>
        internal static string Tours_Service_Yacht {
            get {
                return ResourceManager.GetString("Tours_Service_Yacht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What’s Included.
        /// </summary>
        internal static string Tours_Services_Title {
            get {
                return ResourceManager.GetString("Tours_Services_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We host your perfect celebration on a yacht – captain, route, and vessel provided. You bring the good mood!.
        /// </summary>
        internal static string Tours_Subtitle {
            get {
                return ResourceManager.GetString("Tours_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yacht Tours &amp; Celebrations.
        /// </summary>
        internal static string Tours_Title {
            get {
                return ResourceManager.GetString("Tours_Title", resourceCulture);
            }
        }
    }
}
