//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Survey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Survey() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Pages.Survey", typeof(Pages_Survey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return Home.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take our yachting survey to help us recommend the best sailing program for you: confident start, advanced training, catamaran courses, or individual lessons. Tailor your yachting experience in Montenegro!.
        /// </summary>
        internal static string Meta_Description_Survey {
            get {
                return ResourceManager.GetString("Meta_Description_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yachting Survey — Select Program | VibeOfTheWave.
        /// </summary>
        internal static string PageTitle_Survey {
            get {
                return ResourceManager.GetString("PageTitle_Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Catamaran IYT.
        /// </summary>
        internal static string Programs_Catamaran_Title {
            get {
                return ResourceManager.GetString("Programs_Catamaran_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confident Start.
        /// </summary>
        internal static string Programs_ConfidentStart_Title {
            get {
                return ResourceManager.GetString("Programs_ConfidentStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LEVEL UP.
        /// </summary>
        internal static string Programs_LevelUp_Title {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Power IYT.
        /// </summary>
        internal static string Programs_Power_Title {
            get {
                return ResourceManager.GetString("Programs_Power_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Power &amp; Sail IYT.
        /// </summary>
        internal static string Programs_SailPower_Title {
            get {
                return ResourceManager.GetString("Programs_SailPower_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How experienced are you with sailing?.
        /// </summary>
        internal static string Step1_Question {
            get {
                return ResourceManager.GetString("Step1_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 1: Your Experience.
        /// </summary>
        internal static string Step1_Title {
            get {
                return ResourceManager.GetString("Step1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What do you want to achieve on this course?.
        /// </summary>
        internal static string Step2_Question {
            get {
                return ResourceManager.GetString("Step2_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 2: Your Goals.
        /// </summary>
        internal static string Step2_Title {
            get {
                return ResourceManager.GetString("Step2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When would you like to start?.
        /// </summary>
        internal static string Step3_Question {
            get {
                return ResourceManager.GetString("Step3_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 3: Dates.
        /// </summary>
        internal static string Step3_Title {
            get {
                return ResourceManager.GetString("Step3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you prefer small or large groups?.
        /// </summary>
        internal static string Step4_Question {
            get {
                return ResourceManager.GetString("Step4_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 4: Group Size.
        /// </summary>
        internal static string Step4_Title {
            get {
                return ResourceManager.GetString("Step4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please leave your email or phone for follow-up..
        /// </summary>
        internal static string Step5_Question {
            get {
                return ResourceManager.GetString("Step5_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 5: Contact Info.
        /// </summary>
        internal static string Step5_Title {
            get {
                return ResourceManager.GetString("Step5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your responses have been recorded..
        /// </summary>
        internal static string Survey_Complete {
            get {
                return ResourceManager.GetString("Survey_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start your “{0}” survey.
        /// </summary>
        internal static string Survey_Header {
            get {
                return ResourceManager.GetString("Survey_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please answer these 5 quick questions to tailor your course..
        /// </summary>
        internal static string Survey_Intro {
            get {
                return ResourceManager.GetString("Survey_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank You!.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
    }
}
