//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Fleet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Fleet() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Pages.Fleet", typeof(Pages_Fleet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bow thruster: Yes.
        /// </summary>
        internal static string Fleet_Beneteau_BowThruster {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_BowThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cabins: 2 (4 berths).
        /// </summary>
        internal static string Fleet_Beneteau_Cabins {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Cabins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A modern 10-meter motor yacht with two powerful diesel engines. It has everything needed for comfortable cruising: 2 cabins, hot water, a toilet, and a flybridge with a second helm station. The presence of a bow thruster and modern Raymarine electronics (radar, autopilot, chartplotter) makes training on this yacht very close to real charter conditions..
        /// </summary>
        internal static string Fleet_Beneteau_Desc {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radar, autopilot, chartplotter (Raymarine): Yes.
        /// </summary>
        internal static string Fleet_Beneteau_Electronics {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engines: 2 × 200 HP (diesel).
        /// </summary>
        internal static string Fleet_Beneteau_Engines {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Engines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flybridge with helm: Yes.
        /// </summary>
        internal static string Fleet_Beneteau_Flybridge {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Flybridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length: 32 ft (10 m).
        /// </summary>
        internal static string Fleet_Beneteau_Length {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motor Yacht Beneteau Antares 32.
        /// </summary>
        internal static string Fleet_Beneteau_Name {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot water &amp; WC: Yes.
        /// </summary>
        internal static string Fleet_Beneteau_WC {
            get {
                return ResourceManager.GetString("Fleet_Beneteau_WC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bow thruster: Yes.
        /// </summary>
        internal static string Fleet_Jeanneau_BowThruster {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_BowThruster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cabins: 4 (8 berths).
        /// </summary>
        internal static string Fleet_Jeanneau_Cabins {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_Cabins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A modern 13-meter cruising sailing yacht with 4 cabins. The top-tier Premier equipment package offers maximum comfort and a full set of gear for training. The large sail area (100 m² + 125 m² gennaker) is great for practicing various sailing techniques, and the bow thruster makes docking easier..
        /// </summary>
        internal static string Fleet_Jeanneau_Desc {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draft: 2.2 m.
        /// </summary>
        internal static string Fleet_Jeanneau_Draft {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Equipment: Premier.
        /// </summary>
        internal static string Fleet_Jeanneau_Equipment {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length: 43 ft (13 m).
        /// </summary>
        internal static string Fleet_Jeanneau_Length {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sailing Yacht Jeanneau Sun Odyssey 439.
        /// </summary>
        internal static string Fleet_Jeanneau_Name {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sail area: 100 m² (+ gennaker 125 m²).
        /// </summary>
        internal static string Fleet_Jeanneau_SailArea {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_SailArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot water &amp; WC: Yes.
        /// </summary>
        internal static string Fleet_Jeanneau_WC {
            get {
                return ResourceManager.GetString("Fleet_Jeanneau_WC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We train on new, modern sailing and motor yachts, just like those you can charter anywhere in the world. You should learn on the type of boat you plan to sail..
        /// </summary>
        internal static string Fleet_Subtitle {
            get {
                return ResourceManager.GetString("Fleet_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our Fleet.
        /// </summary>
        internal static string Fleet_Title {
            get {
                return ResourceManager.GetString("Fleet_Title", resourceCulture);
            }
        }
    }
}
