//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared_ContactSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared_ContactSection() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Shared.ContactSection", typeof(Shared_ContactSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        internal static string Contact_Address_Title {
            get {
                return ResourceManager.GetString("Contact_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ul. Morskaya 1, 0 km from marinas.
        /// </summary>
        internal static string Contact_Address_Value {
            get {
                return ResourceManager.GetString("Contact_Address_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Contact_Email_Title {
            get {
                return ResourceManager.GetString("Contact_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на annushcz@gmail.com.
        /// </summary>
        internal static string Contact_Email_Value {
            get {
                return ResourceManager.GetString("Contact_Email_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.google.com/maps?q=50.0463574,14.4390276&amp;z=16&amp;;output=embed.
        /// </summary>
        internal static string Contact_Map_Embed {
            get {
                return ResourceManager.GetString("Contact_Map_Embed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        internal static string Contact_Phone_Title {
            get {
                return ResourceManager.GetString("Contact_Phone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +420-774-343-513.
        /// </summary>
        internal static string Contact_Phone_Value {
            get {
                return ResourceManager.GetString("Contact_Phone_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We’re here to answer any questions!.
        /// </summary>
        internal static string Contact_Subtitle {
            get {
                return ResourceManager.GetString("Contact_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get in Touch.
        /// </summary>
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send Message.
        /// </summary>
        internal static string Form_Button {
            get {
                return ResourceManager.GetString("Form_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Email.
        /// </summary>
        internal static string Form_Email_Placeholder {
            get {
                return ResourceManager.GetString("Form_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error sending message:.
        /// </summary>
        internal static string Form_ErrorPrefix {
            get {
                return ResourceManager.GetString("Form_ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        internal static string Form_Message_Placeholder {
            get {
                return ResourceManager.GetString("Form_Message_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Name.
        /// </summary>
        internal static string Form_Name_Placeholder {
            get {
                return ResourceManager.GetString("Form_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sending….
        /// </summary>
        internal static string Form_Sending {
            get {
                return ResourceManager.GetString("Form_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you, {0}! Your message has been sent..
        /// </summary>
        internal static string Form_SuccessMessage {
            get {
                return ResourceManager.GetString("Form_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://facebook.com/yourpage.
        /// </summary>
        internal static string Social_Facebook {
            get {
                return ResourceManager.GetString("Social_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://instagram.com/yourpage.
        /// </summary>
        internal static string Social_Instagram {
            get {
                return ResourceManager.GetString("Social_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://linkedin.com/company/yourpage.
        /// </summary>
        internal static string Social_LinkedIn {
            get {
                return ResourceManager.GetString("Social_LinkedIn", resourceCulture);
            }
        }
    }
}
