//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared_InfoModal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared_InfoModal() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Shared.InfoModal", typeof(Shared_InfoModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        internal static string Details_Header {
            get {
                return ResourceManager.GetString("Details_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration.
        /// </summary>
        internal static string Duration_Label {
            get {
                return ResourceManager.GetString("Duration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Training options.
        /// </summary>
        internal static string Options_Header {
            get {
                return ResourceManager.GetString("Options_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string Price_Label {
            get {
                return ResourceManager.GetString("Price_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select course.
        /// </summary>
        internal static string Programs_SelectCourse {
            get {
                return ResourceManager.GetString("Programs_SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 days.
        /// </summary>
        internal static string sail_standard_Duration {
            get {
                return ResourceManager.GetString("sail_standard_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 days intensive.
        /// </summary>
        internal static string sail_standard_Option1 {
            get {
                return ResourceManager.GetString("sail_standard_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 240 nautical miles.
        /// </summary>
        internal static string sail_standard_Option2 {
            get {
                return ResourceManager.GetString("sail_standard_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Living on board.
        /// </summary>
        internal static string sail_standard_Option3 {
            get {
                return ResourceManager.GetString("sail_standard_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 450 €.
        /// </summary>
        internal static string sail_standard_Price {
            get {
                return ResourceManager.GetString("sail_standard_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extended IYT course with offshore and night passages.
        /// </summary>
        internal static string sail_standard_Subtitle {
            get {
                return ResourceManager.GetString("sail_standard_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program “Standard”.
        /// </summary>
        internal static string sail_standard_Title {
            get {
                return ResourceManager.GetString("sail_standard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 days.
        /// </summary>
        internal static string sail_vip_Duration {
            get {
                return ResourceManager.GetString("sail_vip_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 days intensive.
        /// </summary>
        internal static string sail_vip_Option1 {
            get {
                return ResourceManager.GetString("sail_vip_Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 200 nautical miles.
        /// </summary>
        internal static string sail_vip_Option2 {
            get {
                return ResourceManager.GetString("sail_vip_Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Private or small group.
        /// </summary>
        internal static string sail_vip_Option3 {
            get {
                return ResourceManager.GetString("sail_vip_Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6 050 €.
        /// </summary>
        internal static string sail_vip_Price {
            get {
                return ResourceManager.GetString("sail_vip_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Individual &amp; intensive for busy people.
        /// </summary>
        internal static string sail_vip_Subtitle {
            get {
                return ResourceManager.GetString("sail_vip_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program “VIP”.
        /// </summary>
        internal static string sail_vip_Title {
            get {
                return ResourceManager.GetString("sail_vip_Title", resourceCulture);
            }
        }
    }
}
