//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared_ReasonsSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared_ReasonsSection() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Shared.ReasonsSection", typeof(Shared_ReasonsSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our curriculum is crafted from years of experience to equip captains with skills for confident solo sailing..
        /// </summary>
        internal static string Reasons_1_Text {
            get {
                return ResourceManager.GetString("Reasons_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom Training Program.
        /// </summary>
        internal static string Reasons_1_Title {
            get {
                return ResourceManager.GetString("Reasons_1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Train in state-of-the-art marinas in Montenegro and Turkey for safe and comfortable learning..
        /// </summary>
        internal static string Reasons_2_Text {
            get {
                return ResourceManager.GetString("Reasons_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modern Marina Locations.
        /// </summary>
        internal static string Reasons_2_Title {
            get {
                return ResourceManager.GetString("Reasons_2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our instructors bring a wealth of expertise to mentor and inspire, making your learning engaging and effective..
        /// </summary>
        internal static string Reasons_3_Text {
            get {
                return ResourceManager.GetString("Reasons_3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expert Instructors.
        /// </summary>
        internal static string Reasons_3_Title {
            get {
                return ResourceManager.GetString("Reasons_3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No matter the season, our courses run all year, allowing you to gain experience in diverse weather conditions..
        /// </summary>
        internal static string Reasons_4_Text {
            get {
                return ResourceManager.GetString("Reasons_4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year-Round Courses.
        /// </summary>
        internal static string Reasons_4_Title {
            get {
                return ResourceManager.GetString("Reasons_4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Join our international network of alumni and continue your adventures with fellow captains..
        /// </summary>
        internal static string Reasons_5_Text {
            get {
                return ResourceManager.GetString("Reasons_5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vibrant Community.
        /// </summary>
        internal static string Reasons_5_Title {
            get {
                return ResourceManager.GetString("Reasons_5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get exclusive deals on yacht charters worldwide thanks to our partnerships with leading charter companies..
        /// </summary>
        internal static string Reasons_6_Text {
            get {
                return ResourceManager.GetString("Reasons_6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Charter Assistance.
        /// </summary>
        internal static string Reasons_6_Title {
            get {
                return ResourceManager.GetString("Reasons_6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6 reasons why our students trust us.
        /// </summary>
        internal static string Reasons_Subtitle {
            get {
                return ResourceManager.GetString("Reasons_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Why choose us.
        /// </summary>
        internal static string Reasons_Title {
            get {
                return ResourceManager.GetString("Reasons_Title", resourceCulture);
            }
        }
    }
}
