//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared_ProgramsSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared_ProgramsSection() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Shared.ProgramsSection", typeof(Shared_ProgramsSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catamaran Training.
        /// </summary>
        internal static string Programs_Catamaran_Alt {
            get {
                return ResourceManager.GetString("Programs_Catamaran_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Catamaran_Duration {
            get {
                return ResourceManager.GetString("Programs_Catamaran_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Catamaran_GroupSize {
            get {
                return ResourceManager.GetString("Programs_Catamaran_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Catamaran_Price {
            get {
                return ResourceManager.GetString("Programs_Catamaran_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Catamaran_Text {
            get {
                return ResourceManager.GetString("Programs_Catamaran_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Catamaran IYT.
        /// </summary>
        internal static string Programs_Catamaran_Title {
            get {
                return ResourceManager.GetString("Programs_Catamaran_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catamaran upskill image.
        /// </summary>
        internal static string Programs_CatamaranAdvanced_Alt {
            get {
                return ResourceManager.GetString("Programs_CatamaranAdvanced_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_CatamaranAdvanced_Duration {
            get {
                return ResourceManager.GetString("Programs_CatamaranAdvanced_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_CatamaranAdvanced_Price {
            get {
                return ResourceManager.GetString("Programs_CatamaranAdvanced_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information coming soon..
        /// </summary>
        internal static string Programs_CatamaranAdvanced_Text {
            get {
                return ResourceManager.GetString("Programs_CatamaranAdvanced_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catamaran+.
        /// </summary>
        internal static string Programs_CatamaranAdvanced_Title {
            get {
                return ResourceManager.GetString("Programs_CatamaranAdvanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group programs from zero on one type of yacht.
        /// </summary>
        internal static string Programs_ConfidentStart_Description {
            get {
                return ResourceManager.GetString("Programs_ConfidentStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CONFIDENT START.
        /// </summary>
        internal static string Programs_ConfidentStart_Title {
            get {
                return ResourceManager.GetString("Programs_ConfidentStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open new categories or refresh your skills.
        /// </summary>
        internal static string Programs_FurtherGrowth_Description {
            get {
                return ResourceManager.GetString("Programs_FurtherGrowth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FURTHER GROWTH.
        /// </summary>
        internal static string Programs_FurtherGrowth_Title {
            get {
                return ResourceManager.GetString("Programs_FurtherGrowth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Individual Training.
        /// </summary>
        internal static string Programs_Individual_Alt {
            get {
                return ResourceManager.GetString("Programs_Individual_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Individual_Duration {
            get {
                return ResourceManager.GetString("Programs_Individual_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Individual_GroupSize {
            get {
                return ResourceManager.GetString("Programs_Individual_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Individual_Price {
            get {
                return ResourceManager.GetString("Programs_Individual_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на —.
        /// </summary>
        internal static string Programs_Individual_Text {
            get {
                return ResourceManager.GetString("Programs_Individual_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Individual Training.
        /// </summary>
        internal static string Programs_Individual_Title {
            get {
                return ResourceManager.GetString("Programs_Individual_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INFO.
        /// </summary>
        internal static string Programs_InfoLink {
            get {
                return ResourceManager.GetString("Programs_InfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yachtmaster Coastal Sail IYT Course.
        /// </summary>
        internal static string Programs_LevelUp_Coastal_Alt {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Coastal_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 days.
        /// </summary>
        internal static string Programs_LevelUp_Coastal_Duration {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Coastal_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 150 €.
        /// </summary>
        internal static string Programs_LevelUp_Coastal_Price {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Coastal_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advance to the next level of certification and prepare for long-distance sailing voyages..
        /// </summary>
        internal static string Programs_LevelUp_Coastal_Text {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Coastal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yachtmaster Coastal Course.
        /// </summary>
        internal static string Programs_LevelUp_Coastal_TitleCard {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Coastal_TitleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensive workshops to refine your sailing skills and confidence.
        /// </summary>
        internal static string Programs_LevelUp_Description {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Atlantic Passage Training.
        /// </summary>
        internal static string Programs_LevelUp_Ocean_Alt {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Ocean_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 weeks.
        /// </summary>
        internal static string Programs_LevelUp_Ocean_Duration {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Ocean_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 750 €.
        /// </summary>
        internal static string Programs_LevelUp_Ocean_Price {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Ocean_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Historic ocean passage: Balearics – Gibraltar – Madeira – Canary Islands..
        /// </summary>
        internal static string Programs_LevelUp_Ocean_Text {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Ocean_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Atlantic Ocean Voyage.
        /// </summary>
        internal static string Programs_LevelUp_Ocean_TitleCard {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Ocean_TitleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LEVEL UP.
        /// </summary>
        internal static string Programs_LevelUp_Title {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekend Sailing Workshops.
        /// </summary>
        internal static string Programs_LevelUp_Weekend_Alt {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Weekend_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4 hours.
        /// </summary>
        internal static string Programs_LevelUp_Weekend_Duration {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Weekend_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 70 €.
        /// </summary>
        internal static string Programs_LevelUp_Weekend_Price {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Weekend_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Learn new techniques or perfect your skills in short, focused sessions..
        /// </summary>
        internal static string Programs_LevelUp_Weekend_Text {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Weekend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weekend Workshops.
        /// </summary>
        internal static string Programs_LevelUp_Weekend_TitleCard {
            get {
                return ResourceManager.GetString("Programs_LevelUp_Weekend_TitleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All types of programs in an individual format.
        /// </summary>
        internal static string Programs_PersonalStart_Description {
            get {
                return ResourceManager.GetString("Programs_PersonalStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PERSONAL START.
        /// </summary>
        internal static string Programs_PersonalStart_Title {
            get {
                return ResourceManager.GetString("Programs_PersonalStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power Yachts Training.
        /// </summary>
        internal static string Programs_Power_Alt {
            get {
                return ResourceManager.GetString("Programs_Power_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6 days.
        /// </summary>
        internal static string Programs_Power_Duration {
            get {
                return ResourceManager.GetString("Programs_Power_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на up to 4 students per group.
        /// </summary>
        internal static string Programs_Power_GroupSize {
            get {
                return ResourceManager.GetString("Programs_Power_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 350 €.
        /// </summary>
        internal static string Programs_Power_Price {
            get {
                return ResourceManager.GetString("Programs_Power_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum speed and independence from wind. Perfect for those who want to get comfortable fast..
        /// </summary>
        internal static string Programs_Power_Text {
            get {
                return ResourceManager.GetString("Programs_Power_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Power IYT.
        /// </summary>
        internal static string Programs_Power_Title {
            get {
                return ResourceManager.GetString("Programs_Power_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power Advanced Training.
        /// </summary>
        internal static string Programs_PowerAdvanced_Alt {
            get {
                return ResourceManager.GetString("Programs_PowerAdvanced_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 days.
        /// </summary>
        internal static string Programs_PowerAdvanced_Duration {
            get {
                return ResourceManager.GetString("Programs_PowerAdvanced_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 850 €.
        /// </summary>
        internal static string Programs_PowerAdvanced_Price {
            get {
                return ResourceManager.GetString("Programs_PowerAdvanced_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Master power yachts and make docking predictable, not a gamble..
        /// </summary>
        internal static string Programs_PowerAdvanced_Text {
            get {
                return ResourceManager.GetString("Programs_PowerAdvanced_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motor+.
        /// </summary>
        internal static string Programs_PowerAdvanced_Title {
            get {
                return ResourceManager.GetString("Programs_PowerAdvanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group programs from zero on two types of yachts.
        /// </summary>
        internal static string Programs_PracticalStart_Description {
            get {
                return ResourceManager.GetString("Programs_PracticalStart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PRACTICAL START.
        /// </summary>
        internal static string Programs_PracticalStart_Title {
            get {
                return ResourceManager.GetString("Programs_PracticalStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sailing Yachts Training.
        /// </summary>
        internal static string Programs_Sail_Alt {
            get {
                return ResourceManager.GetString("Programs_Sail_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 days.
        /// </summary>
        internal static string Programs_Sail_Duration {
            get {
                return ResourceManager.GetString("Programs_Sail_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на up to 5 students per group.
        /// </summary>
        internal static string Programs_Sail_GroupSize {
            get {
                return ResourceManager.GetString("Programs_Sail_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 450 €.
        /// </summary>
        internal static string Programs_Sail_Price {
            get {
                return ResourceManager.GetString("Programs_Sail_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The most popular and universal segment for beginner skippers. Best way to start..
        /// </summary>
        internal static string Programs_Sail_Text {
            get {
                return ResourceManager.GetString("Programs_Sail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Sail IYT.
        /// </summary>
        internal static string Programs_Sail_Title {
            get {
                return ResourceManager.GetString("Programs_Sail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sail Advanced Training.
        /// </summary>
        internal static string Programs_SailAdvanced_Alt {
            get {
                return ResourceManager.GetString("Programs_SailAdvanced_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 days.
        /// </summary>
        internal static string Programs_SailAdvanced_Duration {
            get {
                return ResourceManager.GetString("Programs_SailAdvanced_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 150 €.
        /// </summary>
        internal static string Programs_SailAdvanced_Price {
            get {
                return ResourceManager.GetString("Programs_SailAdvanced_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upgrade your skills on sailing yachts and prepare for independent charters..
        /// </summary>
        internal static string Programs_SailAdvanced_Text {
            get {
                return ResourceManager.GetString("Programs_SailAdvanced_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Sail Advanced.
        /// </summary>
        internal static string Programs_SailAdvanced_Title {
            get {
                return ResourceManager.GetString("Programs_SailAdvanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sail &amp;amp; Power Training.
        /// </summary>
        internal static string Programs_SailPower_Alt {
            get {
                return ResourceManager.GetString("Programs_SailPower_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 13 days.
        /// </summary>
        internal static string Programs_SailPower_Duration {
            get {
                return ResourceManager.GetString("Programs_SailPower_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на up to 5 students per group.
        /// </summary>
        internal static string Programs_SailPower_GroupSize {
            get {
                return ResourceManager.GetString("Programs_SailPower_GroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 300 €.
        /// </summary>
        internal static string Programs_SailPower_Price {
            get {
                return ResourceManager.GetString("Programs_SailPower_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Combined program for a universal license on both sail and power yachts..
        /// </summary>
        internal static string Programs_SailPower_Text {
            get {
                return ResourceManager.GetString("Programs_SailPower_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Skipper Power &amp; Sail IYT.
        /// </summary>
        internal static string Programs_SailPower_Title {
            get {
                return ResourceManager.GetString("Programs_SailPower_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select course.
        /// </summary>
        internal static string Programs_SelectCourse {
            get {
                return ResourceManager.GetString("Programs_SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Types of Training at Sail Band Sailing School.
        /// </summary>
        internal static string Programs_Subtitle {
            get {
                return ResourceManager.GetString("Programs_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PROGRAMS OF STUDY.
        /// </summary>
        internal static string Programs_Title {
            get {
                return ResourceManager.GetString("Programs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motor+.
        /// </summary>
        internal static string Programs_Variant_MotorPlus_Label {
            get {
                return ResourceManager.GetString("Programs_Variant_MotorPlus_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard.
        /// </summary>
        internal static string Programs_Variant_Standard_Label {
            get {
                return ResourceManager.GetString("Programs_Variant_Standard_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIP.
        /// </summary>
        internal static string Programs_Variant_VIP_Label {
            get {
                return ResourceManager.GetString("Programs_Variant_VIP_Label", resourceCulture);
            }
        }
    }
}
