//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLandingPage.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared_ServicesSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared_ServicesSection() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyLandingPage.Resources.Shared.ServicesSection", typeof(Shared_ServicesSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Learn more.
        /// </summary>
        internal static string Service_LearnMore {
            get {
                return ResourceManager.GetString("Service_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Learn to sail from scratch and earn international certification..
        /// </summary>
        internal static string Service1_Desc {
            get {
                return ResourceManager.GetString("Service1_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yacht School.
        /// </summary>
        internal static string Service1_Title {
            get {
                return ResourceManager.GetString("Service1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rent modern yachts and catamarans with full service and support..
        /// </summary>
        internal static string Service2_Desc {
            get {
                return ResourceManager.GetString("Service2_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yacht Charter.
        /// </summary>
        internal static string Service2_Title {
            get {
                return ResourceManager.GetString("Service2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unique routes, adventures, and sea holidays for families and friends..
        /// </summary>
        internal static string Service3_Desc {
            get {
                return ResourceManager.GetString("Service3_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yacht Tours.
        /// </summary>
        internal static string Service3_Title {
            get {
                return ResourceManager.GetString("Service3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rent a yacht without a skipper for experienced sailors. Sail Montenegro on your own!.
        /// </summary>
        internal static string Service4_Desc {
            get {
                return ResourceManager.GetString("Service4_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bareboat Charter Montenegro.
        /// </summary>
        internal static string Service4_Title {
            get {
                return ResourceManager.GetString("Service4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///    yacht-school::Yacht School::Become a certified sailor with our comprehensive courses|
        ///    yacht-charter::Yacht Charter::Charter a yacht for your own adventure|
        ///    yachting-in-montenegro::Yachting in Montenegro::Bareboat charter from Porto Montenegro|
        ///    tours-celebrations::Tours &amp; Celebrations::Host your celebration on a yacht – captain, route and vessel provided. You bring the fun
        ///  .
        /// </summary>
        internal static string Services_List {
            get {
                return ResourceManager.GetString("Services_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What We Offer.
        /// </summary>
        internal static string Services_Title {
            get {
                return ResourceManager.GetString("Services_Title", resourceCulture);
            }
        }
    }
}
