name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:      
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_BAY_05A8ABF03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload

          app_location: "MyLandingPage"
          api_location: "FunctionEmailApi"

          output_location: ""