name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WASM
        run: dotnet publish MyLandingPage/MyLandingPage.csproj -c Release -o MyLandingPage/bin/Release/net8.0/browser-wasm/publish

      - name: Get OIDC ID Token
        id: get_id_token
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const idToken = await core.getIDToken();
            core.setOutput('token', idToken);

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: "MyLandingPage"
          api_location: ""
          output_location: "bin/Release/net8.0/browser-wasm/publish"
          github_id_token: ${{ steps.get_id_token.outputs.token }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
