name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly
        run: |
          dotnet publish MyLandingPage/MyLandingPage.csproj \
            -c Release \
            -o MyLandingPage/bin/Release/net8.0/browser-wasm/publish

      - name: Publish Azure Function API
        run: |
          dotnet publish FunctionEmailApi/FunctionEmailApi.csproj \
            -c Release \
            -o FunctionEmailApi/bin/Release/net8.0/publish

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_BAY_05A8ABF03 }}
          action: upload

          app_location: "MyLandingPage/bin/Release/net8.0/browser-wasm/publish/wwwroot"

          api_artifact_location: "FunctionEmailApi/bin/Release/net8.0/publish"

          skip_app_build: true
          skip_api_build: true