name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - prod
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - prod

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3

      # 1) Устанавливаем .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 2) Публикуем Blazor WASM в нужную папку
      - name: Publish Blazor WebAssembly
        run: |
          dotnet publish MyLandingPage/MyLandingPage.csproj \
            -c Release \
            -o MyLandingPage/bin/Release/net8.0/browser-wasm/publish

      # 3) Деплойим уже готовые файлы и пропускаем Oryx-сборку
      - name: Build And Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_BAY_05A8ABF03 }}
          action: upload
          app_location: "MyLandingPage"
          api_location: ""
          output_location: "bin/Release/net8.0/browser-wasm/publish"
          skip_app_build: true
